.test_build_template: &test_build
  script:
    - export REL_OS_NAME=$(lsb_release -is)
    - export REL_OS_VERS_LONG=$(lsb_release -rs | sed -r "s/^([0-9]+).*/\1/")
    - export REL_PROJECT_NAME=$CI_PROJECT_NAME
    - export REL_TAG=$CI_BUILD_REF_NAME
    - export KARABO_TAG="latest_build"
    - curl http://exflserv05.desy.de/karabo/karaboFramework/tags/$KARABO_TAG/karabo-$KARABO_TAG-Release-$REL_OS_NAME-$REL_OS_VERS_LONG-x86_64.sh > karabo.sh
    - bash karabo.sh --prefix=/root
    - source /root/karabo/activate
    - cd $CI_PROJECT_DIR
    # install depends
    - >
        if test -f "DEPENDS"; then
           IFS=","
           while read line; do
               [[ $line =~ ^#.* ]] && continue
               norm=${line/,/ }
               norm=`echo $norm | sed -e "s/[[:space:]]\+/ /g"`
               device=$(echo $norm | cut -f1 -d' ')
               tag=$(echo $norm | cut -f2 -d' ')
               echo $device
               echo $tag
               karabo -g https://$XFEL_TOKEN@git.xfel.eu install $device $tag
           done < DEPENDS        
        fi;
    - pip install -e . 
    - nosetests .
  only:
    - branches
  except:
    - master

##### Test build #####

test:ubuntu18:
  image: europeanxfel/karabo-ci:ubuntu-18
  <<: *test_build

test:centos7:
  image: europeanxfel/karabo-ci:centos-7
  <<: *test_build

