.test_build_template: &test_build
  script:
    - export REL_OS_NAME=$(lsb_release -is)
    - export REL_OS_VERS_LONG=$(lsb_release -rs | sed -r "s/^([0-9]+).*/\1/")
    - export REL_PROJECT_NAME=$CI_PROJECT_NAME
    - export REL_TAG=$CI_BUILD_REF_NAME
    - export KARABO_TAG="latest_build"
    - curl http://exflserv05.desy.de/karabo/karaboFramework/tags/$KARABO_TAG/karabo-$KARABO_TAG-Release-$REL_OS_NAME-$REL_OS_VERS_LONG-x86_64.sh > karabo.sh
    - bash karabo.sh --prefix=/root
    - source /root/karabo/activate
    - pushd $CI_PROJECT_DIR
    - pip install --upgrade .
    - nosetests .
  only:
    - branches
  except:
    - master

##### Test build #####
test:ubuntu14:
  image: europeanxfel/karabo-ci:ubuntu-14
  <<: *test_build

test:ubuntu16:
  image: europeanxfel/karabo-ci:ubuntu-16
  <<: *test_build

test:centos7:
  image: europeanxfel/karabo-ci:centos-7
  <<: *test_build

